### ISSUE TITLE
Node_name is readonly in dmrcluster

### ISSUE THREAD

**Issue by oeresundsgruppen** [SolaceProducts/terraform-provider-solacebroker#65]
Hi, would like to set nodeName in dmrcluster, but its read-only and hence auto-generated, but needed to create links afterwards.... can it be writeable ?

**Comment by bczoma** [comment]
Hi @oeresundsgruppen , `nodeName` needs to be read-only because of the internal broker logic to generate them. It requires using some Terraform technique to solve this issue, for example using a data source on the dmrCluster.

**Comment by oeresundsgruppen** [comment]
Thanks, read it using terraform data, and just got the name of docker container, which I can set in docker compose...
