### ISSUE TITLE
[Bug]: Periodically get timeout when downloading dependency files in terraform init stage

### ISSUE THREAD

**Issue by diwangcanada** [SolaceProducts/terraform-provider-solacebroker#69]
### Bug Description

In terraform init, some times I got below error:

Output:
Initializing modules...

Initializing Terraform Cloud...

Initializing provider plugins...
- Reusing previous version of solaceproducts/solacebroker from the dependency lock file
╷
│ Error: Failed to install provider
│ 
│ Error while installing solaceproducts/solacebroker v0.9.2: could not query
│ provider registry for registry.terraform.io/solaceproducts/solacebroker:
│ failed to retrieve authentication checksums for provider: the request
│ failed after 3 attempts, please try again later: Get
│ "[https://objects.githubusercontent.com/github-production-release-asset-2e65be/602268380/01c5c3f9-607b-4bf5-a8f1-d7b5eb03519f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240527%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240527T070043Z&X-Amz-Expires=300&X-Amz-Signature=1bc9a610da51c3891153613e4d7965da31485ce39d6a2a5943a2ed6bd5972490&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=602268380&response-content-disposition=attachment%3B%20filename%3Dterraform-provider-solacebroker_0.9.2_SHA256SUMS&response-content-type=application%2Foctet-stream"](https://objects.githubusercontent.com/github-production-release-asset-2e65be/602268380/01c5c3f9-607b-4bf5-a8f1-d7b5eb03519f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240527%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240527T070043Z&X-Amz-Expires=300&X-Amz-Signature=1bc9a610da51c3891153613e4d7965da31485ce39d6a2a5943a2ed6bd5972490&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=602268380&response-content-disposition=attachment%3B%20filename%3Dterraform-provider-solacebroker_0.9.2_SHA256SUMS&response-content-type=application%2Foctet-stream%22):
│ net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)
╵

##[error]Terraform command 'plan' failed with exit code '1'.
##[error]2024-05-27T07:00:32.524Z [INFO]  Terraform version: 1.1.7

### Expected Behavior

Be able to download denpency files and install the provider.
terraform init should be run successfully.

### Steps to Reproduce

This is in our Terraform Enterprise and we got this error all most everyday. 
When this happen, all jobs after it also failed with same error.
We have to wait for one hour+ and re-run the same job without any changes to successfully initialize it.  

### Solace Broker version

10.7.1

### Solace API

solace cloud

**Comment by bczoma** [comment]
I'm closing this as it sounds like a temporary network issue, specific to the user environment. Please also check this with the latest provider version.
