### ISSUE TITLE
Update Provider Config 

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/terraform-provider-solacebroker#77]
Please add more detail to the "Quick Start" and sample so it's 100% clear what URL / username / password people should be using to make sure there aren't hiccups when getting started. 

Quick Start in README (Step 3) 
Sample used: https://github.com/SolaceProducts/terraform-provider-solacebroker/blob/329b0065052242ec7674656f04f2eb37f1a9512c/examples/sampleconfig.tf#L13

**Comment by Mrc0113** [comment]
FYI: a driver of this was the question asked in Community: https://solace.community/discussion/3926/what-url-need-to-use-in-terraform-to-connect-to-message-vpn

**Comment by bczoma** [comment]
Thanks @Mrc0113  - this is the closest in the provider documentation:  https://registry.terraform.io/providers/SolaceProducts/solacebroker/latest/docs#url
Will definitely add more for clarity.

**Comment by bczoma** [comment]
Fixed in latest v1.1.0 release, see example and https://registry.terraform.io/providers/SolaceProducts/solacebroker/latest/docs#example-usage
